= Bulma Java image:https://maven-badges.herokuapp.com/maven-central/com.github.t1/bulma-java/badge.svg[link=https://search.maven.org/artifact/com.github.t1/bulma-java] image:https://github.com/t1/bulma-java/actions/workflows/maven.yml/badge.svg[link=https://github.com/t1/bulma-java/actions/workflows/maven.yml]


NOTE: I'm currently doing this only for my own side projects, so I marked the versions as `alpha` status, i.e. any new versions can contain breaking changes and the documentation is at most rudimentary. If you want to keep up, your best choice is to look at the tests and see what's changed; please speak up if you need a stable API for larger projects by opening an issue. Even better, you can contribute by helping to design a stable API.

A simple servers-side-html library based on Bulma components.

Everything is fluent and chainable, i.e. no builders, no withers.

Simple example:

[source,java]
----
@Path("/")
public class Application {
    @GET
    @Produces(TEXT_HTML)
    public String index() {
        return html("Title Text").body(title("Hello World")).render();
    }
}
----

returns:

[source,html]
----
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Title Text</title>
    </head>
    <body>
        <h1 class="title">Hello World</h1>
    </body>
</html>
----

You can also return the `Renderable` and add a trivial `MessageBodyWriter`.
This is JAX-RS, but works analogous in Spring or whatever.
There are no dependencies!

For more examples, look at the tests and maybe the `all-tests.html` page generated by the tests.

For a little demo based on https://quarkus.io[Quarkus] and https://htmx.org/docs/[HTMX], take a look https://github.com/t1/htmx-quarkus-demo[here].

== Restrictions

Currently, the only icons supported, are https://fontawesome.com[fontawesome].

== Forms and validation

You can include the `validation.css` file in your HTML to get a red asterisk on the label of `required` fields and mark invalid fields with a red border, when the user has changed them.

TODO: document the usage of the `validation.js`

TODO: use the help field to display validation errors. See https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms/Form_validation#a_more_detailed_example[the MDN] for an example of how to do that.

see https://developer.mozilla.org/en-US/docs/Web/HTML/Guides/Constraint_validation
