package com.github.t1.customers.ui;

import com.github.t1.bulmajava.form.Field;
import com.github.t1.customers.Customer;
import jakarta.enterprise.context.Dependent;

import java.util.stream.Stream;

import static com.github.t1.bulmajava.basic.Style.STATIC;
import static com.github.t1.bulmajava.form.Field.field;
import static com.github.t1.bulmajava.form.Input.input;
import static com.github.t1.bulmajava.form.InputType.EMAIL;
import static com.github.t1.bulmajava.form.InputType.TEXT;
import static com.github.t1.bulmajava.form.Select.select;

// TODO generate this class from the Customer class with an annotation processor
//  annotation-ideas: @Input(TEXT, EMAIL, ...), @Readonly (=>static)
//  required and others from Bean Validation
//  we'd like to produce the markup for the https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms/Form_validation#using_built-in_form_validation:
//  * required
//  * minlength, maxlength
//  * min, max, step
//  * type
//  * pattern
public
@Dependent class Customer$Form {
    public Stream<Field> of(Customer customer) {
        //noinspection ThisExpressionReferencesGlobalObjectJS
        return Stream.of(
                field("Customer Number")
                        .content(input(TEXT).is(STATIC).fieldName("customerNumber").value(customer.getId()))
                        .help("This number is generated by the system and is read-only."),
                field("Name")
                        .content(input(TEXT).fieldName("name").autofocus().value(customer.getName())
                                .required().minlength(6).on("input", "validate(this, 'customer name')"))
                        .help("The full name of the customer in latin script."),
                field("Email")
                        .content(input(EMAIL).fieldName("email").value(customer.getEmail())
                                .on("input", "validate(this, 'email')"))
                        .help("We'll send an verification email to this address before activating the account."),
                field("Support Level").content(select("supportLevel")
                                .required().on("input", "validate(this, 'level')")
                                .option("", "Please select:")
                                .option("bronze", "Bronze")
                                .option("silver", "Silver")
                                .option("gold", "Gold")
                                .option("platinum", "Platinum")
                                .selected(Customer.Level.toString(customer.getSupportLevel())))
                        .help("The support level of the customer."));
    }
}
