quarkus:
#  log:
#    category:
#      "io.quarkus":
#        # noinspection QsYaml
#        level: WARN
  swagger-ui:
    always-include: true
    deep-linking: true
    display-request-duration: true
    theme: feeling-blue
    try-it-out-enabled: true
bulma-java-forms-test:
  htmx:
    #debug: true
